export const ActionTypes = {
  SEARCH_EMAIL: "SEARCH_EMAIL",
  SEARCH_PASSWORD: "SEARCH_PASSWORD",
  LOGOUT: "LOGOUT",
  ITEM_DATA: "ITEM_DATA",
  REMOVE_DATA: "REMOVE_DATA",
  DATA_RECORD: "DATA_RECORD",
};
